### PR TITLE
Assignment 1

### PR DESCRIPTION
**Pull request by shweta0310**
A doubt in tutorial 2:
While creating subnets, the DHCP server was getting failed. Why so? Also, how should I correct this?
doubt

### CODE REVIEW

**Comment by isunitha98selvan** [comment]
Did you assign a static IP address to the DHCP server?

**Comment by isunitha98selvan** [comment]
@shweta0310 Check and let me know if you face the same problem.

**Comment by shweta0310** [comment]
Static address to the dhcp server..as in the one given in 1st tutorial
right??
if yes, then I did try it.
Still the problem persists.
Also the router isn't being connected to more than 2 ports.

**Comment by isunitha98selvan** [comment]
@shweta0310 Check these links out:
https://learningnetwork.cisco.com/thread/103244
https://youtu.be/EMqG2h-lsZk

**Pull request merged**
